import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faAlignJustify,
  faAlignLeft,
  faArrowsRotate,
  faBold,
  faBookOpen,
  faBroadcastTower,
  faBrush,
  faCalculator,
  faCalendarCheck,
  faCalendarDays,
  faChartLine,
  faClock,
  faClone,
  faCode,
  faCodeCompare,
  faColumns,
  faCompress,
  faCreditCard,
  faCube,
  faDice,
  faDiceD6,
  faEye,
  faEyeDropper,
  faFileArrowDown,
  faFileCode,
  faFileImage,
  faFingerprint,
  faFireFlameCurved,
  faFont,
  faGaugeHigh,
  faGraduationCap,
  faHashtag,
  faHeartPulse,
  faHourglassHalf,
  faImage,
  faIndent,
  faKey,
  faLaptopCode,
  faLink,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMagnifyingGlassChart,
  faMoon,
  faNetworkWired,
  faPalette,
  faPaw,
  faPercent,
  faPuzzlePiece,
  faQrcode,
  faReceipt,
  faRightLeft,
  faRobot,
  faRotate,
  faRulerCombined,
  faShareNodes,
  faShieldHalved,
  faShuffle,
  faSignature,
  faSortAlphaDown,
  faSwatchbook,
  faTable,
  faTags,
  faTextHeight,
  faTextWidth,
  faTicket,
  faToolbox,
  faUpRightAndDownLeftFromCenter,
  faWandMagicSparkles,
  faWallet,
  faWeightHanging,
  faWeightScale,
} from "@fortawesome/free-solid-svg-icons";

const ICONS: Record<string, IconDefinition> = {
  "karakter-sayaci": faTextWidth,
  "kelime-sayaci": faAlignLeft,
  "harf-donusturucu": faFont,
  "sifre-uretici": faKey,
  "json-formatter": faCode,
  base64: faRightLeft,
  "url-encoder": faLink,
  "bmi-hesaplayici": faHeartPulse,
  "kdv-hesaplayici": faReceipt,
  "yuzde-hesaplayici": faPercent,
  "yas-hesaplayici": faCalendarDays,
  "qr-kod-olusturucu": faQrcode,
  "sha-hash-uretici": faFingerprint,
  "tarih-farki": faHourglassHalf,
  "renk-donusturucu": faPalette,
  "uuid-uretici": faShuffle,
  "birim-donusturucu": faRulerCombined,
  "parola-guc-testi": faGaugeHigh,
  "sayi-donusturucu": faCalculator,
  "regex-testi": faPuzzlePiece,
  "bosluk-temizleyici": faWandMagicSparkles,
  "md5-hash": faHashtag,
  "jwt-cozucu": faShieldHalved,
  "json-csv-donusturucu": faTable,
  "unix-timestamp-cevirici": faClock,
  "tekrar-satir-temizleyici": faClone,
  "ai-token-hesaplayici": faRobot,
  "lorem-ipsum-uretici": faAlignJustify,
  "bahsis-hesaplayici": faWallet,
  "indirim-hesaplayici": faTags,
  "ortalama-hesaplayici": faChartLine,
  "kopek-yasi-hesaplayici": faPaw,
  "subnet-hesaplayici": faNetworkWired,
  "px-rem-donusturucu": faTextHeight,
  "xml-formatter": faFileCode,
  "css-minifier": faBrush,
  "html-minifier": faLaptopCode,
  "wcag-kontrast": faEye,
  "renk-paleti-uretici": faSwatchbook,
  "box-shadow-uretici": faCube,
  "metin-siralayici": faSortAlphaDown,
  "liste-karistirici": faDice,
  "yaml-json-donusturucu": faArrowsRotate,
  "md5-dosya-checksum": faFileArrowDown,
  "resim-sikistirici": faCompress,
  "resim-boyutlandirici": faUpRightAndDownLeftFromCenter,
  "resim-donusturucu": faImage,
  "resimden-base64": faFileImage,
  "resimden-renk-secici": faEyeDropper,
  "slug-uretici": faSignature,
  "meta-tag-uretici": faShareNodes,
  "anahtar-kelime-yogunlugu": faMagnifyingGlassChart,
  "serp-onizleme": faMagnifyingGlass,
  "okunabilirlik-skoru": faBookOpen,
  "metin-karsilastirici": faColumns,
  "html-entity-cevirici": faCodeCompare,
  "morse-cevirici": faBroadcastTower,
  "metin-ters-cevirici": faRotate,
  "kalin-italik-metin": faBold,
  "caesar-sifre": faLockOpen,
  "not-ortalamasi": faGraduationCap,
  "kredi-emi": faCreditCard,
  "kalori-bmr": faFireFlameCurved,
  "vucut-yag-orani": faWeightScale,
  "ideal-kilo": faWeightHanging,
  "uyku-hesaplayici": faMoon,
  "cron-test": faCalendarCheck,
  "html-formatter": faIndent,
  "aes-sifreleme": faLock,
  "rastgele-string-uretici": faDiceD6,
  "jwt-uretici": faTicket,
};

export default function ToolIcon({
  id,
  className,
}: {
  id: string;
  className?: string;
}) {
  return (
    <FontAwesomeIcon
      icon={ICONS[id] ?? faToolbox}
      className={className}
      aria-hidden="true"
    />
  );
}