import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
faAlarmClock,
  faAlignJustify,
  faAlignLeft,
  faArrowsLeftRight,
  faArrowsRotate,
  faAt,
  faBold,
  faBolt,
  faBookOpen,
  faBroadcastTower,
  faBrush,
  faCalculator,
  faCalendarCheck,
  faCalendarDays,
  faCamera,
  faChartColumn,
  faChartLine,
  faClock,
  faClone,
  faCode,
  faCodeCompare,
  faCoins,
  faColumns,
  faCompass,
  faCompress,
  faCreditCard,
  faCrop,
  faCube,
  faDatabase,
  faDice,
  faDiceD6,
  faDiceSix,
  faDivide,
  faArrowTrendUp,
  faCaretRight,
  faCheckDouble,
  faCircleDot,
  faClockRotateLeft,
  faCropSimple,
  faDoorOpen,
  faFaceLaughSquint,
  faFaceSmile,
  faFile,
  faGamepad,
  faGasPump,
  faGrip,
  faHandFist,
  faHourglassStart,
  faHouseChimney,
  faImages,
  faKeyboard,
  faLayerGroup,
  faMaximize,
  faQuoteLeft,
  faQuoteRight,
  faRulerVertical,
  faTerminal,
  faVault,
  faWaveSquare,
  faEarthAmericas,
  faEnvelope,
  faEye,
  faEyeDropper,
  faFileArrowDown,
  faFileCode,
  faFileImage,
  faFingerprint,
  faFireFlameCurved,
  faFont,
  faGaugeHigh,
  faGem,
  faGlobe,
  faGraduationCap,
faHardDrive,
  faHashtag,
  faHeartPulse,
  faHourglassHalf,
  faImage,
  faIndent,
  faInfinity,
  faKey,
  faLaptopCode,
  faLink,
  faListOl,
  faLock,
  faLockOpen,
  faMagnifyingGlass,
  faMagnifyingGlassChart,
  faMoneyBillTrendUp,
  faMoon,
  faNetworkWired,
  faPalette,
  faPaw,
  faPercent,
  faPiggyBank,
  faPuzzlePiece,
  faQrcode,
  faReceipt,
  faRightLeft,
  faRobot,
  faRotate,
  faRotateRight,
  faRulerCombined,
  faServer,
  faShareNodes,
  faShieldHalved,
  faShuffle,
  faSignature,
  faSitemap,
  faSortAlphaDown,
  faSquare,
  faSquareBinary,
  faStamp,
  faStopwatch,
  faSwatchbook,
  faTable,
  faTags,
  faTextHeight,
  faTextSlash,
  faTextWidth,
  faThermometerHalf,
  faTicket,
  faToolbox,
  faTrophy,
  faUpRightAndDownLeftFromCenter,
  faUserLock,
  faVolumeHigh,
  faWandMagicSparkles,
  faWallet,
  faWeightHanging,
  faWeightScale,
} from "@fortawesome/free-solid-svg-icons";

export const TOOL_ICONS: Record<string, IconDefinition> = {
  "character-counter": faTextWidth,
  "word-counter": faAlignLeft,
  "case-converter": faFont,
  "password-generator": faKey,
  "json-formatter": faCode,
  base64: faRightLeft,
  "url-encoder": faLink,
  "bmi-calculator": faHeartPulse,
  "vat-calculator": faReceipt,
  "percentage-calculator": faPercent,
  "age-calculator": faCalendarDays,
  "qr-code-generator": faQrcode,
  "sha-hash-generator": faFingerprint,
  "date-difference": faHourglassHalf,
  "color-converter": faPalette,
  "uuid-generator": faShuffle,
  "unit-converter": faRulerCombined,
  "password-strength-checker": faGaugeHigh,
  "number-base-converter": faCalculator,
  "regex-tester": faPuzzlePiece,
  "whitespace-cleaner": faWandMagicSparkles,
  "md5-hash": faHashtag,
  "jwt-decoder": faShieldHalved,
  "json-csv-converter": faTable,
  "unix-timestamp-converter": faClock,
  "duplicate-line-remover": faClone,
  "ai-token-counter": faRobot,
  "lorem-ipsum-generator": faAlignJustify,
  "tip-calculator": faWallet,
  "discount-calculator": faTags,
  "average-calculator": faChartLine,
  "dog-age-calculator": faPaw,
  "subnet-calculator": faNetworkWired,
  "px-rem-converter": faTextHeight,
  "xml-formatter": faFileCode,
  "css-minifier": faBrush,
  "html-minifier": faLaptopCode,
  "wcag-contrast-checker": faEye,
  "color-palette-generator": faSwatchbook,
  "box-shadow-generator": faCube,
  "text-sorter": faSortAlphaDown,
  "list-shuffler": faDice,
  "yaml-json-converter": faArrowsRotate,
  "md5-file-checksum": faFileArrowDown,
  "image-compressor": faCompress,
  "image-resizer": faUpRightAndDownLeftFromCenter,
  "image-converter": faImage,
  "image-to-base64": faFileImage,
  "image-color-picker": faEyeDropper,
  "slug-generator": faSignature,
  "meta-tag-generator": faShareNodes,
  "keyword-density-checker": faMagnifyingGlassChart,
  "serp-preview": faMagnifyingGlass,
  "readability-score": faBookOpen,
  "text-diff": faColumns,
  "html-entity-converter": faCodeCompare,
  "morse-converter": faBroadcastTower,
  "text-reverser": faRotate,
  "fancy-text-generator": faBold,
  "caesar-cipher": faLockOpen,
  "gpa-calculator": faGraduationCap,
  "loan-emi-calculator": faCreditCard,
  "calorie-bmr-calculator": faFireFlameCurved,
  "body-fat-calculator": faWeightScale,
  "ideal-weight-calculator": faWeightHanging,
  "sleep-calculator": faMoon,
  "cron-tester": faCalendarCheck,
  "html-formatter": faIndent,
  "aes-encryption": faLock,
  "random-string-generator": faDiceD6,
  "jwt-generator": faTicket,
  "currency-converter": faCoins,
  "compound-interest-calculator": faChartLine,
  "salary-calculator": faMoneyBillTrendUp,
  "sql-formatter": faDatabase,
  "json-xml-converter": faCode,
  "markdown-html-converter": faBold,
  "hmac-generator": faFingerprint,
  "html-table-generator": faTable,
  "favicon-generator": faSquare,
  "image-crop": faCrop,
  "image-watermark": faStamp,
  "jsonld-generator": faTags,
  "hreflang-generator": faGlobe,
  "robots-txt-generator": faRobot,
  "wheel-of-names": faTrophy,
  "random-number-generator": faDiceD6,
  "stopwatch-timer": faStopwatch,
  "time-zone-converter": faEarthAmericas,
  "qr-code-reader": faCamera,
  "text-extractor": faEnvelope,
  "css-gradient-generator": faPalette,
  "border-radius-generator": faSquare,
  "text-to-speech": faVolumeHigh,
  "pomodoro-timer": faAlarmClock,
  "binary-text-converter": faSquareBinary,
  "credit-card-validator": faCreditCard,
  "roman-numeral-converter": faCalculator,
  "temperature-converter": faThermometerHalf,
  "calculator": faCalculator,
  "html-to-text-converter": faTextSlash,
  "chmod-calculator": faUserLock,
  "dice-roller": faDiceSix,
  "coin-flipper": faCoins,
  "word-frequency-counter": faChartColumn,
  "prime-factors-calculator": faDivide,
  "angle-converter": faCompass,
  "data-size-converter": faHardDrive,
  "fibonacci-generator": faInfinity,
  "mortgage-calculator": faHouseChimney,
  "hours-calculator": faClockRotateLeft,
  "income-tax-calculator": faVault,
  "inflation-calculator": faArrowTrendUp,
  "typing-speed-test": faKeyboard,
  "css-units-converter": faRulerVertical,
  "css-triangle-generator": faCaretRight,
  "countdown-timer": faHourglassStart,
  "image-grid-splitter": faGrip,
  "ascii-art-generator": faTerminal,
  "pixelate-image": faCropSimple,
  "vigenere-cipher": faDoorOpen,
  "punctuation-remover": faQuoteLeft,
  "anagram-solver": faWaveSquare,
  "keyword-combiner": faLayerGroup,
  "title-length-checker": faMaximize,
  "magic-8-ball": faCircleDot,
  "fuel-cost-calculator": faGasPump,
  "plagiarism-checker": faCheckDouble,
  "number-to-words": faListOl,
  "image-rotator": faRotateRight,
  "xml-sitemap-generator": faSitemap,
  "email-validator": faAt,
  "word-scrambler": faShuffle,
  "hashtag-generator": faHashtag,
  "acronym-generator": faFont,
  "palindrome-checker": faQuoteLeft,
  "http-status-codes": faServer,
  "csv-formatter": faTable,
  "days-until-calculator": faCalendarDays,
  "running-pace-converter": faStopwatch,
  "savings-goal-calculator": faPiggyBank,
  "rock-paper-scissors": faHandFist,
  "horoscope": faGem,
  "text-escape-unescape": faTerminal,
  "emoji-remover": faFaceSmile,
  "reading-time-calculator": faClockRotateLeft,
  "totp-generator": faShieldHalved,
  "url-parser": faLink,
  "js-minifier": faCode,
  "mime-type-finder": faFile,
  "percentage-change-calculator": faPercent,
  "fuel-economy-calculator": faGaugeHigh,
  "electricity-cost-calculator": faBolt,
  "calories-burned-calculator": faFireFlameCurved,
  "image-combiner": faImages,
  "image-flipper": faArrowsLeftRight,
  "sitemap-url-extractor": faSitemap,
  "joke-generator": faFaceLaughSquint,
  "random-quote-generator": faQuoteRight,
  "guess-the-number": faGamepad,
};

export default function ToolIcon({
  id,
  className,
}: {
  id: string;
  className?: string;
}) {
  return (
    <FontAwesomeIcon
      icon={TOOL_ICONS[id] ?? faToolbox}
      className={className}
      aria-hidden="true"
    />
  );
}