import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faAlignJustify,
  faAlignLeft,
  faArrowsRotate,
  faBrush,
  faCalculator,
  faCalendarDays,
  faChartLine,
  faClock,
  faClone,
  faCode,
  faCube,
  faDice,
  faEye,
  faFileArrowDown,
  faFileCode,
  faFingerprint,
  faFont,
  faGaugeHigh,
  faHashtag,
  faHeartPulse,
  faHourglassHalf,
  faKey,
  faLaptopCode,
  faLink,
  faNetworkWired,
  faPalette,
  faPaw,
  faPercent,
  faPuzzlePiece,
  faQrcode,
  faReceipt,
  faRightLeft,
  faRobot,
  faRulerCombined,
  faShieldHalved,
  faShuffle,
  faSortAlphaDown,
  faSwatchbook,
  faTable,
  faTags,
  faTextHeight,
  faTextWidth,
  faToolbox,
  faWandMagicSparkles,
  faWallet,
} from "@fortawesome/free-solid-svg-icons";

const ICONS: Record<string, IconDefinition> = {
  "karakter-sayaci": faTextWidth,
  "kelime-sayaci": faAlignLeft,
  "harf-donusturucu": faFont,
  "sifre-uretici": faKey,
  "json-formatter": faCode,
  base64: faRightLeft,
  "url-encoder": faLink,
  "bmi-hesaplayici": faHeartPulse,
  "kdv-hesaplayici": faReceipt,
  "yuzde-hesaplayici": faPercent,
  "yas-hesaplayici": faCalendarDays,
  "qr-kod-olusturucu": faQrcode,
  "sha-hash-uretici": faFingerprint,
  "tarih-farki": faHourglassHalf,
  "renk-donusturucu": faPalette,
  "uuid-uretici": faShuffle,
  "birim-donusturucu": faRulerCombined,
  "parola-guc-testi": faGaugeHigh,
  "sayi-donusturucu": faCalculator,
  "regex-testi": faPuzzlePiece,
  "bosluk-temizleyici": faWandMagicSparkles,
  "md5-hash": faHashtag,
  "jwt-cozucu": faShieldHalved,
  "json-csv-donusturucu": faTable,
  "unix-timestamp-cevirici": faClock,
  "tekrar-satir-temizleyici": faClone,
  "ai-token-hesaplayici": faRobot,
  "lorem-ipsum-uretici": faAlignJustify,
  "bahsis-hesaplayici": faWallet,
  "indirim-hesaplayici": faTags,
  "ortalama-hesaplayici": faChartLine,
  "kopek-yasi-hesaplayici": faPaw,
  "subnet-hesaplayici": faNetworkWired,
  "px-rem-donusturucu": faTextHeight,
  "xml-formatter": faFileCode,
  "css-minifier": faBrush,
  "html-minifier": faLaptopCode,
  "wcag-kontrast": faEye,
  "renk-paleti-uretici": faSwatchbook,
  "box-shadow-uretici": faCube,
  "metin-siralayici": faSortAlphaDown,
  "liste-karistirici": faDice,
  "yaml-json-donusturucu": faArrowsRotate,
  "md5-dosya-checksum": faFileArrowDown,
};

export default function ToolIcon({
  id,
  className,
}: {
  id: string;
  className?: string;
}) {
  return (
    <FontAwesomeIcon
      icon={ICONS[id] ?? faToolbox}
      className={className}
      aria-hidden="true"
    />
  );
}